### ISSUE TITLE
Web TCP Server or Web Socket Server

### ISSUE THREAD

**Issue by itprodavets** [NModbus/NModbus#102]
I want to create a web server so that with some options I can change the server settings by calling the controller and its functions.

When creating a console version of the server, I can connect to it through the simulator. But when I do the same in the web version, I can't connect to the server. I use

Is there a way to create something like this using a library?

Console:
![image](https://user-images.githubusercontent.com/5946414/156882903-0a49bac5-2981-4e81-a5cf-081af8253313.png)

Connected:
![image](https://user-images.githubusercontent.com/5946414/156882929-e21efdaf-4d3f-45d7-ad0d-7e733471160e.png)

Web Api:
![image](https://user-images.githubusercontent.com/5946414/156883038-31c11aaa-a39d-470c-ac0d-35a263135f8e.png)

No connection:
![image](https://user-images.githubusercontent.com/5946414/156883016-af10a57d-3009-4eb0-9b45-24e8ef6a6520.png)

netstat -a
![image](https://user-images.githubusercontent.com/5946414/156883102-886e0e27-f242-4555-9cce-a4a924bf3736.png)

**Comment by rquackenbush** [comment]
Sorry for the late reply on this. Can you show the code where you're launching the `ModbusTcpSlave` in the WebApi?
