### ISSUE TITLE
Writing slaves is complicated as one should custom implement ISlaveDataStore in order to respond to data changes properly

### ISSUE THREAD

**Issue by glmnet** [NModbus/NModbus#11]
I realized after a while I had to use a custom implementation of ISlaveDataStore to react to changes in the DataStore, this is confusing specially because in previous versions of the library there were event handlers for this.
I believe a custom implementation of ISlaveDataStore that will fire and event *only when the change is initiated from a Modbus master write* (or otherwise include change event source in event arguments) should be provided.

**Comment by rquackenbush** [comment]
I ended up going with a more bare implementation of the slave data store than was previously provided as I felt it was too limiting. 

I can see where providing an implementation of ‘ISlaveDataStore’ that more closely mimics the legacy data store would make the transition easier and reduce boilerplate code. I’ll add that soon.

**Comment by joncutting** [comment]
I see the same issue as glmnet in a project that am I working on...has there been any progress here?

**Comment by AlexanderNitsch** [comment]
I would love that as well. Did anyone already write a DataStore which has this feature? Some sample code to start would be nice. (An official release even nicer :) )

**Comment by rquackenbush** [comment]
The `SlaveDataStore` class now exposes the underlying `PointSource<T>` instances (rather than `IPointSource<T>`). This includes the following events:

```c#
public event EventHandler<PointEventArgs> BeforeRead;
public event EventHandler<PointEventArgs<T>> BeforeWrite;
public event EventHandler<PointEventArgs> AfterWrite;
```

This will be included in the next release.
