### ISSUE TITLE
Message queue implementation

### ISSUE THREAD

**Issue by kzoltaan** [NModbus/NModbus#113]
I used my very simple modbus implementation until this time. My communication layer has 2 message queue: read (Poll) queue, and write queue. I drop the raw(builded) request with callback into the queue, and when it was ready the callback called with the received and parsed data. Write queue has a priority over poll queue. This message queue run in thread with semaphores. So it is async. My communication layer was a shared resource. Other parts of the code also can communicate on this line.

I have "Table class" with own poll timers. "Modbus read" attached to Poll event.

I have approx 30-40 modbus tables to poll with different poll times. When I use async methods (ReadHoldingRegistersAsync) to read, it indicate a lot of timeout exception and uncertain opeation. 

Now I'm using simpe ReadHoldingRegisters but I have to hack Serialportadapter with System.Threading.Thread.Sleep(40) in wirte operation. Now its looks good. Okay, It is ready, it is working. 
But I want to use other device with other protocols on this serial line.

My question is, how can I implement my previous message queue communication layer as a new and nice portadapter which is IStreamResource? 

Do you have any idea?

**Comment by rquackenbush** [comment]
I’ve actually implemented something like this in an IoT application using
RabbitMQ as a message broker / queue. I don’t see how you could use an
IStreamResource to accomplish this.

IStreamResource is transport later and has no concept of whether the master
is reading or writing. I implemented a façade on top of IModbusMaster that
handed all of the concurrency concerns.  If I remember correctly I
leveraged the AsyncLock available in the Nito AsyncEx nuget package.

I’ve also implemented a Modbus scheduled reader along the lines of what you
described. In that case, I used a simple while loop and just did Task.Delay
to wait for the next scheduled operation.  That actually obviated the need
for complex locking.

I hope that helps. Unfortunately, I don’t have access to any of the code
mentioned above.  Let me know if a pseudo-code example would be helpful.
