### ISSUE TITLE
Regression ReadHoldingRegisters32 in 3.0.78

### ISSUE THREAD

**Issue by fasigno** [NModbus/NModbus#129]
Hello,
I encounter regression with ReadHoldingRegisters32  function in 3.0.78.

I have a project targeting version 3.0.72 and worked fine until package upgrade. 

I read 8 registers of uints

`var result1 = modbusMaster.ReadHoldingRegisters32(MODBUS_ADDRESS, startAddress, 8);`

With 3.0.72:

> [Trace]        TX: 01 03 03 00 00 10 44 42
> [Trace]        RX: 01 03 20 11 02 FF F8 04 42 FF FE 2E 32 00 0A 2E 32 00 0A 2E 32 00 0A 2E 32 00 0A 2E 32 00 0A 2E 32 00 0A E3 B3

With 3.0.78:

> [Trace]        TX: 01 03 03 00 00 08 44 48
> [Trace]        RX: 01 03 10 11 02 FF F8 04 42 FF FE 2E 32 00 0A 2E 32 00 0A F8 D5
> [Error]        IOException, 3 retries remaining - System.IO.IOException: Unexpected byte count. Expected 32, received 16.
>                   at NModbus.Message.ReadHoldingInputRegisters32Request.ValidateResponse(IModbusMessage response)
>                   at NModbus.IO.ModbusTransport.ValidateResponse(IModbusMessage request, IModbusMessage response)
>                   at NModbus.IO.ModbusTransport.UnicastMessage[T](IModbusMessage message)

Number of registers seems wrong so byte count check throws.

If I increase number of registers to be read, byte count check increases constraints accordingly

> [Trace]        TX: 01 03 03 00 00 10 44 42
> [Trace]        RX: 01 03 20 11 02 FF F8 04 42 FF FE 2E 32 00 0A 2E 32 00 0A 2E 32 00 0A 2E 32 00 0A 2E 32 00 0A 2E 32 00 0A E3 B3
> [Error]        IOException, 3 retries remaining - System.IO.IOException: Unexpected byte count. Expected 64, received 32.
>                   at NModbus.Message.ReadHoldingInputRegisters32Request.ValidateResponse(IModbusMessage response)
>                   at NModbus.IO.ModbusTransport.ValidateResponse(IModbusMessage request, IModbusMessage response)
>                   at NModbus.IO.ModbusTransport.UnicastMessage[T](IModbusMessage message)

Regards.

**Comment by cnzgray** [comment]
The method ReadHoldingRegisters32 is in the EnronModbus class, and it is for the PLC of the Enron brand. In his document, a register is **4 bytes** (the document address is: https://simplymodbus.ca/enron_FC03.htm).

According to the data you provided above, it seems that the PLC you use should be **2 bytes**, so you should not directly use the extension method provided by EnronModbus.

Here is a workaround code for your reference:
```csharp
static class ModbusMasterExtensions
{
    private const uint WORD_SIZE = 32u;

    public static uint[] ReadHoldingRegisters32(this IModbusMaster master, byte slaveAddress, ushort startAddress, ushort numberOfPoints)
    {
        var bytes = RegisterFunctions.ReadRegisters(slaveAddress, startAddress, numberOfPoints, master, WORD_SIZE, Endian.LittleEndian);
        return RegisterFunctions.ByteValueArraysToUInts(bytes);
    }

    public static void WriteSingleRegister32(this IModbusMaster master, byte slaveAddress, ushort startAddress, uint data)
    {
        WriteMultipleRegisters32(master, slaveAddress, startAddress, new[] { data });
    }

    public static void WriteMultipleRegisters32(this IModbusMaster master, byte slaveAddress, ushort startAddress, uint[] data)
    {
        RegisterFunctions.WriteRegistersFunc(
            slaveAddress,
            startAddress,
            RegisterFunctions.UIntToByteValueArrays(data, WORD_SIZE),
            master,
            WORD_SIZE,
            Endian.LittleEndian);
    }
}
```
