### ISSUE TITLE
Error read 4 word 32 Register Lovato

### ISSUE THREAD

**Issue by CarlosBelloErla** [NModbus/NModbus#138]
Hi!

I try to read Lovato DMG620 Modbus Energy meter but when i try to read the total energy i have a error with measures.

Lovato address and info
![image](https://github.com/NModbus/NModbus/assets/106149989/f7e783e2-0041-4b84-972e-71b65964d78b)

This a incremental counter but the tcp frames not resolving correct by function Nmodbus readregisters

![image](https://github.com/NModbus/NModbus/assets/106149989/624acebd-6941-4dc9-8910-b371f234309c)
(Fail at 12:27 timestamp)

I captured trafic with Wireshark and at 12:16 the data frame is:
![image](https://github.com/NModbus/NModbus/assets/106149989/0ff1dbdd-8624-4ee8-b0b9-881624c466df)

And 12:27 (Error modbus) is 
![image](https://github.com/NModbus/NModbus/assets/106149989/0324efaa-b3d3-4c10-82ba-a7e0efa36cb3)

The frame is correct but the log with capture function is:

![image](https://github.com/NModbus/NModbus/assets/106149989/62e2c7b7-7e1b-4047-ab45-995ae3983dff)

This is my code

`            try {
                ushort[] inputs = master.ReadInputRegisters(slaveAdress, startAddress, numPoints);

                for (int j = 0; j < numPoints; j++) {
                    auxString += inputs[j].ToString();
                    if (inputs[0] == 65535)
                        intValueAux += inputs[j] - ((inputs[j] > 32767) ? 65536 : 0);
                    else
                        intValueAux += inputs[j];

                    hexFinal += intValueAux.ToString("X");
                }

                intValue = int.Parse(hexFinal, System.Globalization.NumberStyles.HexNumber);
			}`

**Comment by rquackenbush** [comment]
Here is an analysis of the raw TCP data you posted:

12:16 `00010000000b050408000000000000fcdb`

|Hex Data|Field|Decimal Value| 
|---|---|---|
|0x0001|Transaction Identifier|1|
|0x0000|Protocol Identifier|0 = MODBUS|
|0x000b|Length|11|
|0x05|Unit Identifier|5|
|0x04|Function Code|4 - ReadInputRegisters|
|0x08|Byte Count|8|
|0x0000|Reg[0]|0|
|0x0000|Reg[1]0|
|0x0000|Reg[2]|0|
|0xfcdb|Reg[3]|64731|

12:27 `00010000000b0504080000000000001012`

|Hex Data|Field|Decimal Value| 
|---|---|---|
|0x0001|Transaction Identifier|1|
|0x0000|Protocol Identifier|0 = MODBUS|
|0x000b|Length|11|
|0x05|Unit Identifier|5|
|0x04|Function Code|4 - ReadInputRegisters|
|0x08|Byte Count|8|
|0x0000|Reg[0]|0|
|0x0000|Reg[1]0|
|0x0000|Reg[2]|0|
|0xfcdb|Reg[3]|4114|

Is the problem that the value 4114 at 12:27 doesn't match 43.98?

**Comment by rquackenbush** [comment]
Also, I'm concerned about this line:

```c#
hexFinal += intValueAux.ToString("X");
```
It looks like you're not padding the number, so you could run into issues there.

**Comment by cbelloHIB** [comment]
Hi!

Thanks for your answer. The problem was the convert the byte values to Hex values and then to Int. Because when you have a four registers array the conversion change.

Thanks!
