### ISSUE TITLE
Recieve Response after action

### ISSUE THREAD

**Issue by adrianfernandeziturcemi** [NModbus/NModbus#140]
Hello, i am testing this library for research purposes. Is there any way to receive the response of the slave after a write / read etc. ?

I am using ModBus RTU (serial)

Thank you in advance.

**Comment by MPapst** [comment]
Hi,

what kind of response are you expecting?
Most write function codes do not have a response. If you do not get an exception, the write operation has completed successfull.

**Comment by rquackenbush** [comment]
For operations that return data, just the data is returned:

```c#
ushort[] holdingRegisters = modbusMaster.ReadMultipleHoldingRegisters(1, 10);
```

For operations that don't return data, nothing is returned:

```c#
modbusMaster.WriteMultipleRegisters(1, new ushort[0, 1, 2, 3, 4, 5]);
```

To handle errors, you have to wrap the call in a Try/Catch clause:

```c#
try
{
   modbusMaster.WriteMultipleRegisters(1, new ushort[0, 1, 2, 3, 4, 5]);
}
catch(Exception ex)
{
   //TODO: Log ex
}
```

**Comment by rquackenbush** [comment]
If you have any additional questions, please let us know. Closing for now.
