### ISSUE TITLE
System.InvalidCastException: 'Unable to cast object of type 'System.IO.Ports.SerialPort' to type 'NModbus.IO.IStreamResource'.'

### ISSUE THREAD

**Issue by Zapnologica** [NModbus/NModbus#159]
Good day, I am struggling to use Nmodbus to read from a serial port.

I eventually figured out that you need to import another NUGet for the serial to work.  Once I added that to my solution.

```
      using (var serialPort = new SerialPort(SensorConfig.DeviceComport, 9600, Parity.None, 8))
                {
                    try
                    {
                        if (!serialPort.IsOpen)
                        {
                            serialPort.Open();
                        }

                        // create modbus master
                        var mbf = new ModbusFactory();
                        var modbusMaster = mbf.CreateRtuMaster((NModbus.IO.IStreamResource)serialPort);
                        }
```

I have had to cast the serial port to  '(NModbus.IO.IStreamResource)'  However this doesn't make sense?

In the sample code one just passes the raw serialPort into the 'CreateRtuMaster"

![image](https://github.com/NModbus/NModbus/assets/3656913/404152a5-709c-4669-b8ac-66ee82614db6)

Any help would be greatly apperciated.

**Comment by MPapst** [comment]
See #158 
You need to install the NModbus.Serial Package. This one contains an extension Method for the ModbusFactory, that takes a SerialPort as argument: https://github.com/NModbus/NModbus/blob/13a454bdc8dd4b5c0399090a5544927235046a65/NModbus.Serial/ModbusFactoryExtensions.cs#L7
