### ISSUE TITLE
Exception: The requested address is not valid in its context

### ISSUE THREAD

**Issue by kelilive** [NModbus/NModbus#164]
Communicating via Modbus RTU over TCP/IP Protocol. I don't know why it went wrong. Can you guide me?

![image](https://github.com/NModbus/NModbus/assets/142982913/098d0266-0d24-4df4-9ac3-41d1f65bc940)
![image](https://github.com/NModbus/NModbus/assets/142982913/8f3f95ea-45de-475d-8efb-902736110157)

Stack Trace:
```
at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
at System.Net.Sockets.Socket.Bind(EndPoint localEP)
at System.Net.Sockets.TcpListener.Start(Int32 backlog)
```

**Comment by MPapst** [comment]
A TCPListener listenes on a given IP address of the local computer.

So, if you are trying to listen on an ip, the current computer needs an interface with that ip assigned to it.

If you are connecting from and to the same pc, you can use the loopback address. If not on the same pc, you can use the "any" address.
Both can be used from static properties of the IPAddress class (IPAddress.Any).

**Comment by kelilive** [comment]
These two addresses are both LAN addresses, although they are not very similar. They can be pinged normally and all firewalls have been turned off. Because I can read data normally using Modbus Poll, but I don't know how to implement it using NModbus. My local IP is 196.196.198.152.

Can you elaborate on what the code should do? Grateful!

**Comment by MPapst** [comment]
If 196.196.198.152 is your local IP of your computer - the computer is directly connected to the internet without any firewall/router?

Try: 
```csharp
TcpListener listener = new TcpListener(IPAddress.Any, port);
```

**Comment by kelilive** [comment]
![image](https://github.com/NModbus/NModbus/assets/142982913/26aeded1-1e9f-4dae-9d36-ead58e47c250)

```csharp
public static ushort[] ReadHoldingRegisters()
{
    const byte slaveId = 1;
    const int port = 20108;

    var listener = new TcpListener(IPAddress.Any, port);

    listener.Start();

    var factory = new ModbusFactory();
    var network = factory.CreateSlaveNetwork(listener);

    var slave = factory.CreateSlave(slaveId);

    network.AddSlave(slave);
    network.ListenAsync();

    var address = new IPAddress(new[] { (byte)196, (byte)196, (byte)196, (byte)49 });
    using var client = new TcpClient(new IPEndPoint(address, port));
    var master = factory.CreateMaster(client);

    return master.ReadHoldingRegisters(0, 52, 2);
}
```

**Comment by MPapst** [comment]
Have a look in the documentation. There is a difference in creating the TcpClient while using an IPEndPoint or using a string for the IP/using the ConnectAsync method.
https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient?view=net-8.0#constructors

**Comment by kelilive** [comment]
I have basically mastered the usage of tcp, although I don't use it much, the problem now is that the interface is not working.

**Comment by kelilive** [comment]
```csharp
RawModbusRtuOverTcp.Test1();

Console.WriteLine("--------");
RawModbusRtuOverTcp.Test2(1, 1);

Console.WriteLine("--------");
RawModbusRtuOverTcp.Test3(1, 1);

Console.WriteLine("--------");
RawModbusRtuOverTcp.Test4(1, 1);
```

I tried a more primitive approach, but I don't know how to parse this data that returns normal int, float, double. The following is a description of the problems I have encountered. I hope some warm-hearted friends can give me some help.

When I run it for the first time, `Test1`, `Test2`, and `Test3` can get the raw byte array normally, and reading a simple length of data is the same result. However, if `Test4` cannot be obtained, it will be stuck at the time of Receive and cannot proceed to the next line. I have slightly improved the code. I don't know what the problem is. Now only the first one can return the result, and the other 3 can't return the data.

[RawModbusRtuOverTcp.zip](https://github.com/JamesNK/Newtonsoft.Json/files/13741940/RawModbusRtuOverTcp.zip)

**Comment by kelilive** [comment]
I connected the COM port smoothly. The key is that I feel that there are many disadvantages in this way, so I still want to use tcp directly.

According to my understanding, it should be the most concise form. It has already been encapsulated. As for the most complicated writing method, I did not understand it. The feeling should be realized by the simplest writing method. Now calling the api will not return any results to me. The stuck line cannot continue to execute.

I don't want to dwell on why the top initial writeup doesn't pass now, I don't think there should be an IModbusSlave involved since I'm just the client requesting data. The same should be true for listening to the TcpListener object above. So, for now, you can disregard the code involved above. If you count these, there are 4 ways to do it, and I feel that these two are less conventional approaches.

Should be suitable for the two routes: 1. is to use the Nmodbus direct read, the following reference to the following code, but still can not pass 2. is how to correctly parse the data out of their own, I am now returning data are problematic, refer to the Test1, Test2, Test3, Test4. If the simple parse hope that the two problems can be communicated to solve the problem, I will continue to study the back.

```csharp
public static void Main()
{
    var client = new TcpClient();

    client.Connect("196.196.196.49", 20108);

    var factory = new ModbusFactory();
    var master = factory.CreateMaster(client);
    var registers = master.ReadHoldingRegisters(1, 52, 2);
    var data = ModbusUtility.GetSingle(registers[0], registers[1]);

    Console.WriteLine(data);
}
```

![image](https://github.com/NModbus/NModbus/assets/142982913/967a07d9-3da9-4bc9-ac30-11245a700322)

**Comment by kelilive** [comment]
After thinking and raising awareness, it should be that there are two types of TCP RTU messages and Modbus standard messages. 

At present, tcp-based rtu is very stable, but if modbus tcp has a standard message with 6 bytes, it will not work, only rarely can it have a return result, and the return result is also the value of the first address. Two possibilities, the hardware can not handle the standard protocol message? I will communicate with the manufacturer to ask, I hope their technical staff can give me a reply. The second possibility is that my code is wrong. I have updated the latest code.

But the **NModbus** way of parsing is currently confused.

[TestDemo.zip](https://github.com/NModbus/NModbus/files/13752352/TestDemo.zip)

**Comment by MPapst** [comment]
NModus takes the Modbus standard as is.

What you can do is to capture the traffic using Wireshark and see if Wireshark can decode the traffic as Modbus properly or not.

**Comment by Magniveo** [comment]
![2023-12-22 (1)](https://github.com/NModbus/NModbus/assets/5388016/ca178966-51ee-4e41-965b-0ea16754c018)
I used this library more than 4 years, all protocols work.

**Comment by kelilive** [comment]
Later, on the one hand, I deepened my understanding, and on the other hand, I used more scientific methods to analyze and investigate. Including the research on packet capture software you mentioned. I no longer do tests that have poor control perception. I virtualized the serial port myself using virtual serial port software. Then Modbus Slave and Modbus Poll easily passed various tests, except for the ASCII protocol. Then cooperate with ILSPY to find matching classes and methods, and finally the test passes. After figuring out how to make the code, replacing the IP and port of the serial port server was successfully completed. Failure to pass the Modbus Poll test for the TCP standard protocol means that the configuration cannot communicate normally. It is almost not easy to communicate when I send commands myself, so I can understand and accept them.

```
public static float ReadHoldingRegisters(string host, int port, ushort startAddress, ushort length)
{
    using var client = new TcpClient();

    client.Connect(host, port);

    var factory = new ModbusFactory();
    var adapter = new TcpClientAdapter(client);
    var master = factory.CreateRtuMaster(adapter);
    var registers = master.ReadHoldingRegisters(1, startAddress, length);

    return ModbusUtility.GetSingle(registers[0], registers[1]);
}
```

![Modbus](https://github.com/NModbus/NModbus/assets/142982913/d1fadff2-85d3-4b31-bb39-e6ddd3c6777a)
![image](https://github.com/NModbus/NModbus/assets/142982913/09031d07-e150-4e61-88f7-7ad92404afc7)

**Comment by weirdyang** [comment]
> ![2023-12-22 (1)](https://private-user-images.githubusercontent.com/5388016/292560589-ca178966-51ee-4e41-965b-0ea16754c018.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDAwNjMsIm5iZiI6MTczMzM5OTc2MywicGF0aCI6Ii81Mzg4MDE2LzI5MjU2MDU4OS1jYTE3ODk2Ni01MWVlLTRlNDEtOTY1Yi0wZWExNjc1NGMwMTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDVUMTE1NjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQxNWJmZGQ1MWNjMmFkNTJmZjZjOTgwZmFiMDFjOWM4YjgxMDE5Y2E2NDIyMDU4MzNlYzE1ZWE0MjA4NDkxZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.QtmOjQUvgqSAUU62gd1c0hTq_0ROw3omF2by-6ybqDY) I used this library more than 4 years, all protocols work.

is this project available for reference?

**Comment by Magniveo** [comment]
> > ![2023-12-22 (1)](https://private-user-images.githubusercontent.com/5388016/292560589-ca178966-51ee-4e41-965b-0ea16754c018.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0MDAwNjMsIm5iZiI6MTczMzM5OTc2MywicGF0aCI6Ii81Mzg4MDE2LzI5MjU2MDU4OS1jYTE3ODk2Ni01MWVlLTRlNDEtOTY1Yi0wZWExNjc1NGMwMTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDVUMTE1NjAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQxNWJmZGQ1MWNjMmFkNTJmZjZjOTgwZmFiMDFjOWM4YjgxMDE5Y2E2NDIyMDU4MzNlYzE1ZWE0MjA4NDkxZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.QtmOjQUvgqSAUU62gd1c0hTq_0ROw3omF2by-6ybqDY) I used this library more than 4 years, all protocols work.
> 
> is this project available for reference?

Im writed project for self, with stack electrondotnet and blazor he have very more error. May be in future i will port him to the MAUI and then will publish. May be will interest this project.
https://github.com/AndreyAbdulkayumov/TerminalProgram
