### ISSUE TITLE
Async all the way

### ISSUE THREAD

**Issue by MrGAmba01** [NModbus/NModbus#171]
Hi, 

In our application we make heavy use of the async paradigm. On the outside the NModbus library supports an async version (ConcurrentModbusMaster), which just wraps the synchronous functions in a Task.StartNew. As this does work, it is not a preferable solution, as the underlying method
```c#
  <T> UnicastMessage<T>(IModbusMessage message) 
```
calls Thread.Sleep() which causes quite some loss of performance. 

I've created a local branch with a refactor of the library using async methods throughout, Task.Delay and SemaphoreSlim (instead of lock) which gives quite the performance boost for our ModbusRTU application. 

There are currently still some open issues with this modification:
- Only fully implemented for ModbusRTU, some of the other transport layers have been modified (where an easy async solution was available), others are in a broken state.
- Synchronous methods (original interface) need to call the async version (which can be done without deadlocks: [link](https://learn.microsoft.com/en-us/archive/technet-wiki/23103.c-avoiding-deadlock-in-asyncawait))
- Test harness has not yet been updated with async methods

Would this be an interesting upgrade to the library? If so, I can spend some time addressing the above issues.

```c#
   public virtual async Task<T> UnicastMessageAsync<T>(IModbusMessage message)
       where T : IModbusMessage, new()
   {
       IModbusMessage response = null;
       int attempt = 1;
       bool success = false;

       do
       {
           try
           {
               await semaphore.WaitAsync();
               {
                   await WriteAsync(message);
                   bool readAgain;
                   do
                   {
                       readAgain = false;
                       response = await ReadResponseAsync<T>();
                       var exceptionResponse = response as SlaveExceptionResponse;

                       if (exceptionResponse != null)
                       {
                           // if SlaveExceptionCode == ACKNOWLEDGE we retry reading the response without resubmitting request
                           readAgain = exceptionResponse.SlaveExceptionCode == SlaveExceptionCodes.Acknowledge;

                           if (readAgain)
                           {
                               Logger.Debug($"Received ACKNOWLEDGE slave exception response, waiting {_waitToRetryMilliseconds} milliseconds and retrying to read response.");
                               await Task.Delay(WaitToRetryMilliseconds);
                           }
                           else
                           {
                               throw new SlaveException(exceptionResponse);
                           }
                       }
                       else if (ShouldRetryResponse(message, response))
                       {
                           readAgain = true;
                       }
                   }
                   while (readAgain);
               }

               ValidateResponse(message, response);
               success = true;
           }
           catch (SlaveException se)
           {
               if (se.SlaveExceptionCode != SlaveExceptionCodes.SlaveDeviceBusy)
               {
                   throw;
               }

               if (SlaveBusyUsesRetryCount && attempt++ > _retries)
               {
                   throw;
               }

               Logger.Warning($"Received SLAVE_DEVICE_BUSY exception response, waiting {_waitToRetryMilliseconds} milliseconds and resubmitting request.");

               await Task.Delay(WaitToRetryMilliseconds);
           }
           catch (Exception e)
           {
               if (e is SocketException || e.InnerException is SocketException)
               {
                   throw;
               }
               else if (e is FormatException ||
                   e is NotImplementedException ||
                   e is TimeoutException ||
                   e is IOException)
               {
                   Logger.Error($"{e.GetType().Name}, {(_retries - attempt + 1)} retries remaining - {e}");

                   if (attempt++ > _retries)
                   {
                       throw;
                   }

                   await Task.Delay(WaitToRetryMilliseconds);
               }
               else
               {
                   throw;
               }
           }
           finally
           {
               semaphore.Release();
           }
       }
       while (!success);

       return (T)response;
   }
```

**Comment by Magniveo** [comment]
Need more test for work with serialport.

**Comment by MrGAmba01** [comment]
Ah right, well the implementation is already there for the ModbusRTU (just not copied into the post). 

My question is, would it be worth the effort to refactor the whole library to internally work asynchronous. (With some wrapper methods to keep the original sync interface available)

**Comment by MPapst** [comment]
Please have a Look at the next Version in a seperate repository in this organization.

**Comment by MrGAmba01** [comment]
Using the 4.0 version of NModbus would mean a major rewrite of our current codebase... however I does bring a lot of other benefits. I'll have to think about this.

**Comment by Magniveo** [comment]
> Please have a Look at the next Version in a seperate repository in this organization.

Not found work with the serial port. Next version support only ModbusTCP. This library more flexible than next version.

**Comment by ArchieCoder** [comment]
@MrGAmba01 That would have been wonderful the usage of Async. With my UWP app, I have unexpected timeouts due to the bad implementation of SerialPort by Microsoft. The SerialDevice seems more solid based on what I read.
