### ISSUE TITLE
SerialPortStreamAdapter must be reference 2.1.2 version

### ISSUE THREAD

**Issue by pigwing** [NModbus/NModbus#23]
hi i am update NModbus.SerialPortStream 3.0.55 and SerialPortStream 2.1.4 bug SerialPortStreamAdapter must be reference 2.1.2 version

**Comment by AJamesEdwards** [comment]
var modbusFactory = new ModbusFactory();

            string serialPortName = SerialPortStream.GetPortNames().First();
            using (var comport = new SerialPortStream(serialPortName, 19200, 8, Parity.Even, StopBits.One))
            {
                comport.Open();

                using (var adapter = new SerialPortStreamAdapter(comport)) //<== see error message below
                {

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0012	The type 'SerialPortStream' is defined in an assembly that is not referenced. You must add a reference to assembly 'RJCP.SerialPortStream, Version=2.1.2.0, Culture=neutral,

**Comment by pigwing** [comment]
i found that use serialPortStream 2.1.4 will let the cpu 100%....so...use the 2.1.2 is correct

**Comment by AJamesEdwards** [comment]
Thanks that Worked !!!
