### ISSUE TITLE
High and low order is inverted

### ISSUE THREAD

**Issue by sympthom** [NModbus/NModbus#26]
Hi,

High and low order is inverted.

        public static uint GetUInt32(ushort highOrderValue, ushort lowOrderValue)
        {
            byte[] value = BitConverter.GetBytes(lowOrderValue)
                .Concat(BitConverter.GetBytes(highOrderValue))
                .ToArray();

            return BitConverter.ToUInt32(value, 0);
        }

//Martin

**Comment by Fuchks** [comment]
Seems to work as expected: [Fiddle] (https://dotnetfiddle.net/K4bqlS)
