### ISSUE TITLE
How can I read and write negative numbers?

### ISSUE THREAD

**Issue by xzoth** [NModbus/NModbus#28]
I'm a novice, the first time using Modbus protocol for communication, after a simple attempt, I found that nmodbus uses USHORT data type for reading and writing, then how to read and write negative numbers? Thank you

**Comment by MPapst** [comment]
Hi,
you will need to convert the input format (e.g. signed integer or even floating numbers) into its bit representation.
The reason why an ushort is used for modbus is that registers are organized in 16 Bits.

```C#
int inputValue = -15;
byte[] inputBytes = BitConverter.GetBytes(inputValue); 
// inputBytes now contains 4(!) bytes with the bit representation... 
// now you will need to convert them to ushort --> 
// two bytes = 1 ushort, the ordering depends on your system architecture.. google for Endianess

// one way is
ushort lower = inputBytes[0] + (inputBytes[1] << 8);
ushort upper = inputBytes[2] + (inputBytes[3] << 8);
```

Please note that the code is completely untested and does not have any security mechanisms like try/catch or null checks.

**Comment by xzoth** [comment]
Thank you very much. 

I found other ways from google:
`ushrotValue=intValue-((intValue>32767)?65536:0);`
or
`ushortValue=BitConverter.ToUInt16(BitConverter.GetBytes(intValue),0);`
