### ISSUE TITLE
ExecuteCustomMessage not accessible

### ISSUE THREAD

**Issue by Fuchks** [NModbus/NModbus#3]
It would be nice to have custom messages.
Please make ExecuteCustomMessage from ModbusMaster accessible, the functionality is already there ;-)

**Comment by rquackenbush** [comment]
@Fuchks  - I've added the `ExecuteCustomMessage` to the `IModbusMaster` interface. It is available as of version `3.0.34` of the NuGet package.

**Comment by Fuchks** [comment]
:+1:
thx!
