### ISSUE TITLE
Max. register address = 100!!??

### ISSUE THREAD

**Issue by dazzalogan** [NModbus/NModbus#32]
Hi there,

Everything has been working well until I went to writesingleregister to address 4000, where I was told the max. address is 100!?

I need to write to addresses up to 65535. How can I achieve this?

Thanks
Darren

**Comment by MPapst** [comment]
Hi,
can you tell what exactly you are doing (some piece of code) and what error/exception you are getting?
I am reading registers in range of 40k without any issue.

**Comment by dazzalogan** [comment]
Hi there,

Actually, I'm using Nmodbus4 and not Nmodbus, so my question may not be entirely relevant, but I suspect the same issue is with both?

All I'm trying to do is write (via serial port / RTU) a single register (address 4000) with a value, but I receive an error message telling me address 4000 is not valid. 

Actual code: 

MbMaster.WriteSingleRegister(Node, Adr, Val)

Where node = 1, Adr = 4000 and Val is 5491.

Here's the complete error message:
Exception of type 'Modbus.SlaveException' was thrown.

Function Code: 134

Exception Code: 2 - The data address received in the query is not an allowable address for the server (or slave). More specifically, the combination of reference number and transfer length is invalid. For a controller with 100 registers, the PDU addresses the first register as 0, and the last one as 99. If a request is submitted with a starting register address of 96 and a quantity of registers of 4, then this request will successfully operate (address-wise at least) on registers 96, 97, 98, 99. If a request is submitted with a starting register address of 96 and a quantity of registers of 5, then this request will fail with Exception Code 0x02 “Illegal Data Address” since it attempts to operate on registers 96, 97, 98, 99 and 100, and there is no register with address 100.

Thanks

**Comment by MPapst** [comment]
In general then shouldn't you asking there?

This exception is not related to your code. This comes from the slave that you are trying to address. The register is just not available there.

**Comment by dazzalogan** [comment]
Yes, I have since asked there and await a response, however I'm rather desperate for help asap.

Register 4000 does exist on the hardware. I can read/write it with other Modbus utilities so it does appear to be the nmodbus4 library at fault.

**Comment by MPapst** [comment]
I've seen several issues with Modbus over the years. The most important thing may be that every manufacturer of software or devices has a different interpretation of the Modbus Standard. Sometimes they are starting to count at 1, sometimes at 0 with the registers for example.

So what I would do in your case is analyze what is actually going through the line. In my cases it is mostly Modbus/TCP so I can use wireshark to analyze the TCP Packages. I think for RS485 there will be other sniffing tools.
Figure out what the difference is when you are writing with other tools vs the C# Modbus Library you are using.

**Comment by rquackenbush** [comment]
@dazzalogan - by any chance is the registry address off by one? Some Modbus devices (and their documentation) refer to addresses as base 0, and others as base 1. Have you tried writing to register 3999?

**Comment by dazzalogan** [comment]
All,

Thanks for your inputs, but actually it was a stupid mistake on my behalf.
No - it wasn't a index offset issue, it was just me being a dimwit!

Very sorry for wasting your time.

Please close (and burn!) this.
