### ISSUE TITLE
Some modbus support is not a very standard device, there is a problem

### ISSUE THREAD

**Issue by jackswei** [NModbus/NModbus#34]
I sent id 1 address 72 get 1 it's no data
I sent Id 1 address 72 get 2 it's have data, but only one data , so in NModbus happen wrong, but others modbus softwere is ok,i think it no strict. 

how can slove in  very standard device problem?

**Comment by MPapst** [comment]
Hi,
this is a very common issue with modbus and different device manufacturers (or used libraries on device side). 
The background is that some libraries are starting to count at 0 and some at 1.

This is nothing that is special with the nmodbus lib. The easiest way to figure out how you need to create your modbus request is to create a wireshark (for ModbusTCP) or a RS485 Capture (for RTU) and compare that with the two tools/libraries you are using on PC side.

**Comment by AJamesEdwards** [comment]
Or poll an address ( eg. FC4 register # 30) with a know value in it and add
/ subtract one from the address until you receive the correct value.

Note: NModbus uses the FC and the register index into an array. So don't
try to poll FC4 address 30,030. Instead poll FC4 address 30.

**Comment by jackswei** [comment]
I TRY USE RMMS OF MODBUS TOOL  ,IT IS OK. I THING GET 2 DATE ,BUT ONLY SNED 1 DATE,SO NMODBUS    'S DROP THIS.
![2018-12-05_17-18-55](https://user-images.githubusercontent.com/6355204/49729597-e585e080-fcb0-11e8-80fb-d2fc040cdb98.jpg)
![2018-12-05_17-19-37](https://user-images.githubusercontent.com/6355204/49729607-eb7bc180-fcb0-11e8-9bd3-662db04e7a52.jpg)
![2018-12-06_10-42-35](https://user-images.githubusercontent.com/6355204/49729614-ef0f4880-fcb0-11e8-897c-2afcfb3b657e.jpg)
