### ISSUE TITLE
Could not load file or assembly 'Nmodbus.Serial' version >= 3.0.46.0

### ISSUE THREAD

**Issue by JoG-Vivaticket** [NModbus/NModbus#37]
Hi,
In versions from 3.0.46.0, if you implement NModbus.Serial in a UWP Project, this exception appears:
"Could not load file or assembly 'NModbus. Serial, Version=3. 0.46.0, Culture=neutral, PublicKeyToken=null'. File not found."
Output assembly is named "NModbus. Serial. UWP".
I've been tested in previous previous versions 3.0.38 / 3.0.40 / 3.0.41 and this works fine.
Possible to solve this in the latest version?
Thanks

**Comment by gsulc** [comment]
I'm not the project manager, but I've run into similar issues loading packages. It may have to do with the removal of targeting .NET Framework. I think the Serial package targets only .NET Standard. I would like the framework target to be brought back again, but in the meantime, check what build your package targets. The minimum .NET Framework target is 4.6.1, I believe.
