### ISSUE TITLE
DataStore.DataStoreWrittenTo is missing what have it been replaced with ?

### ISSUE THREAD

**Issue by henrikstromberg** [NModbus/NModbus#4]

**Comment by rquackenbush** [comment]
I felt that the existing implementation of `DataStore` was limiting, so I allow an implementation of `ISlaveDataStore` to be passed in when creating a Modbus slave. This allows you to handle storage (and access / events) however you would like.

I've done this in the [Modbus Register Viewer](https://github.com/CaptiveAire/ModbusRegisterViewer/tree/master/ModbusTools.SlaveSimulator/Model) project.

If it's helpful, I could add a default implementation of the `ISlaveDataStore` that exposes some useful functionality.

**Comment by henrikstromberg** [comment]
Thanks for your quick reply. I will look in to the Interface tomorrow but a default implementation would be helpful or add a implementation to the sample project.

/Henrik

Sent from my iPhone

On 15 Aug 2017, at 18:03, rquackenbush <notifications@github.com<mailto:notifications@github.com>> wrote:


I felt that the existing implementation of DataStore was limiting, so I allow an implementation of ISlaveDataStore to be passed in when creating a Modbus slave. This allows you to handle storage (and access / events) however you would like.

I've done this in the Modbus Register Viewer<https://github.com/CaptiveAire/ModbusRegisterViewer/tree/master/ModbusTools.SlaveSimulator/Model> project.

If it's helpful, I could add a default implementation of the ISlaveDataStore that exposes some useful functionality.

**Comment by rquackenbush** [comment]
I've added an example (at the moment it's in the `develop` branch. It's in the method called `StartModbusSerialRtuSlaveWithCustomStore`.
