### ISSUE TITLE
Where is NModbus.chm

### ISSUE THREAD

**Issue by schungx** [NModbus/NModbus#44]
Please tell me where is the elusive `NModbus.chm` which supposedly holds the documentation?

**Comment by AlexanderNitsch** [comment]
I found it in the previous version, that this one was forked from: https://github.com/NModbus4/NModbus4/blob/master/NModbus.chm

But it would be nice, if it were in the repo.

**Comment by AlexanderNitsch** [comment]
Does not seem to fit the new implementation fully, though... But its a starting point

**Comment by rquackenbush** [comment]
Here is the updated documentation:

https://nmodbus.github.io/api/NModbus.html

**Comment by kjetilgloppen** [comment]
FYI: It was removed in commit bec1a51346df0f. 
Not sure if it was intentional or not, but the commit message doesn't mention this change.

**Comment by rquackenbush** [comment]
Yes - it was removed on purpose. chm is a pretty outdated format. I've updated the README.md to point to the latest.
