### ISSUE TITLE
DebugModbusLogger is null in release build (Nuget has release build)

### ISSUE THREAD

**Issue by zii-dmg** [NModbus/NModbus#60]
I can't use `DebugModbusLogger` because compiler removed `Debug.WriteLine` in release build. Maybe we should create `TraceModbusLogger` with `Trace.WriteLine`? In current state `DebugModbusLogger` is not very useful (only for custom debug builds).

**Comment by rquackenbush** [comment]
Excellent point. I've committed `TraceModbusLogger` and it will be available in the next release.
