### ISSUE TITLE
Serial Issues

### ISSUE THREAD

**Issue by TinkerStinker** [NModbus/NModbus#63]
It seems that something has happened to the serial functionality for this project. 
NModbus.Serial is not available and the sample code to create an RTU master doesn't work.

IModbusMaster master = factory.CreateRtuMaster(port);

It wants an ITransport type (if I remember correctly) and will not allow a serial port as the input parameter. I installed the project using nuget and could not get it to work.

**Comment by rquackenbush** [comment]
Did you install the `NModbus.Serial Nuget` package? It's separate from the `NModbus` package.

**Comment by TinkerStinker** [comment]
Wow! I completely missed that. I am sorry to waste your time.  I installed the serial nuget and all is well.
