### ISSUE TITLE
I cannot find the SerialDevice API

### ISSUE THREAD

**Issue by LGinC** [NModbus/NModbus#7]
I want to use Modbus Communication on RPi3, Win10 IoT Core,
but I can't find the APIs about SerialDevice.  Are there jus TCP and UPD?

**Comment by rquackenbush** [comment]
There is an additional NuGet package you need:

https://www.nuget.org/packages/NModbus.Serial/

Unfortunately, that package doesn't target .NET Core quite yet, which I believe is necessary for Win10 IoT Core. I do have a work item for this, but it hasn't been done quite yet:

https://github.com/NModbus/NModbus/issues/2
