### ISSUE TITLE
don't exist overload serial port on method "CreateRtuMaster" on "ModbusFactory" 

### ISSUE THREAD

**Issue by ehsan69h** [NModbus/NModbus#70]
when I use the code of sample method "ModbusSerialRtuMasterWriteRegisters". I get this error:
"cannot convert from 'System.IO.Ports.SerialPort' to 'NModbus.IO.IStreamResource"

this error because the overload method with serial port param doesn't exist in the library!

**Comment by jgmdavies** [comment]
@ehsan69h

Please see issue #72 (closed) for the solution.
Jim
