### ISSUE TITLE
Samples are outdated

### ISSUE THREAD

**Issue by kaamil1984** [NModbus/NModbus#72]
Hi guys,

I have downloaded current NuGet package (3.0.62) and I'm trying to run it on .NET Core 5.0 preview6.

I took function that creates ModbusRtuMaster with SerialPort transport and it seems that it is outdated.

    SerialPort port = ...
    IModbusMaster master = factory.CreateRtuMaster(port);  // there is no such method in ModbusFactory!

Could you update samples application please?

Or give some information how to create ModbusRtuMaster on SerialPort in current version?

**Comment by jgmdavies** [comment]
I think these days you need to include 'NModbus.Serial' from Nuget, and then do something like:

var adapter = new SerialPortAdapter(serialPort);
result = factory.CreateRtuMaster(adapter);

HTH,
Jim

**Comment by kaamil1984** [comment]
Nope. There is no such thing like `SerialPortAdapter` in my 3.0.62 :(

Constructor wants IModbusTransport.

**Comment by jgmdavies** [comment]
@kaamil1984 

I'm also using 3.0.62.  Did you install 'NModbus.Serial' (also 3.0.62) from Nuget in your project(s)?

Actually you can now use just:
`result = factory.CreateRtuMaster(serialPort);`

as 'NModbus.Serial' includes an appropriate extension.

**Comment by kaamil1984** [comment]
Oh dear. It works. 

**Installing additional package NModbus.Serial from NuGet helped.**

Thank you!

**Comment by jgmdavies** [comment]
@kaamil1984

That's good!  Always a shock when things work...
