### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by JulianWigman** [NModbus/NModbus#74]
Hi 
What is the preferred method for handling exceptions with this library.
Obviously try-catch blocks but are there any standard exception codes I can trap from the ModbusFactory.

**Comment by rquackenbush** [comment]
Hi @JulianWigman - I'm not sure exactly what you're looking for... Are you talking about runtime Modbus error messages from the network or specifically when creating objects using `ModbusFactory`? 

Any kind of code example would be useful.

**Comment by JulianWigman** [comment]
Exactly.  Runtime Modbus error messages.

**Comment by MPapst** [comment]
You can find all Exceptions defined (and throwed) by the NModbus library directly in GitHub:
https://github.com/NModbus/NModbus/search?q=Exception
