### ISSUE TITLE
Max limit on Registers with ReadHoldingRegister

### ISSUE THREAD

**Issue by JulianWigman** [NModbus/NModbus#75]
The documentation states that for ReadCoils method you read between 1 and 2000 items but for Holding Registers no max limit is mentioned and I cant believe as a UINT16 it is 65536.

So is there a max limit?

**Comment by MPapst** [comment]
The Limit depends on two things:
* The Modbus Specification limits the registers to max 125 registers to be read at once (https://modbus.org/docs/Modbus_Application_Protocol_V1_1b.pdf page 15)
* There may be a limitation based on the Server you are connecting to. This may not only be an implementation issue lacking the specification, but you may not be allowed to read registers that are not existing on the server.
