### ISSUE TITLE
Git tag for NuGet releases?

### ISSUE THREAD

**Issue by bdube** [NModbus/NModbus#81]
Hi,

Thank you for your work on this library.

I'm wondering if there is a way to correlate the NuGet releases with the commit they come from and I'm overlooking it? It looks like it might be the signed and verified commits. Is that right?

Thank you.

**Comment by rquackenbush** [comment]
That sounds like a great idea. I will work on tagging the package with git commit. 

I will also work on integrating the commit id into the dll themselves (in the information version attribute) so that it's available in code / windows explorer.

**Comment by rquackenbush** [comment]
I've added this for NModbus.v4
