### ISSUE TITLE
nuget package missing serial

### ISSUE THREAD

**Issue by bsa-coder** [NModbus/NModbus#84]
I see serial, etc. in your repo; but, it is missing from your nuget packages

**Comment by rquackenbush** [comment]
Is this what you're looking for?

https://www.nuget.org/packages/NModbus.Serial/

**Comment by MPapst** [comment]
There is an additional package available for the serial component:
https://www.nuget.org/packages/NModbus.Serial/

**Comment by bsa-coder** [comment]
Thanks for the reply ... didn't think to look there.  Makes sense since TCP comes is much more common these days.   No need to bloat a project. Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Marco Papst ***@***.***> Date: 3/13/21  07:54  (GMT-05:00) To: NModbus/NModbus ***@***.***> Cc: Scott Alexander ***@***.***>, Author ***@***.***> Subject: Re: [NModbus/NModbus] nuget package missing serial (#84) 
There is an additional package available for the serial component:
https://www.nuget.org/packages/NModbus.Serial/
