### ISSUE TITLE
write ok,but have error

### ISSUE THREAD

**Issue by jackswei** [NModbus/NModbus#89]
use TC MODBUS
Connect vigor plc rs485,it write ok,but show error
"Unexpected start address in response. Expected 5000, received 0."

I think some devices will not send back
I PASS 
 // message specific validation
            //var req = request as IModbusRequest;

            //if (req != null)
            //{
            //    req.ValidateResponse(response);
            //}

**Comment by rquackenbush** [comment]
Have you confirmed that the serial port settings are correct? E.g. baud
rate, parity, etc?

Also - what RS-485 transceiver are you using?

**Comment by jackswei** [comment]
it's tcp modbus
i use test code 
 using (TcpClient client = new TcpClient("172.16.30.111", 502))
            {
                var factory = new ModbusFactory();
                IModbusMaster master = factory.CreateMaster(client);

                master.WriteSingleRegister(1, 5000, 120);
                var V = master.ReadHoldingRegisters(1, 5000, 1);

            }

**Comment by rquackenbush** [comment]
Are you able to verify that the write worked using some other tool or user interface?
