### ISSUE TITLE
factory.CreateRtuTransport((port) ???

### ISSUE THREAD

**Issue by wwowa-rus** [NModbus/NModbus#91]
Не удается привести... Ошибка.
Unable to cast ... Error.
 using (SerialPort port = new SerialPort("COM3"))
            {              
                var factory = new ModbusFactory();
              IModbusRtuTransport transport = factory.CreateRtuTransport((port);
.....
           }
**Аргумент 1: не удается преобразовать из(Argument 1: Cannot convert from) "System.IO.Ports.SerialPort" в "NModbus.IO.IStreamResource".**	
И где пространство имен NModBus.Serial  ???	
And where is the namespace NModBus.Serial ???

**Comment by MPapst** [comment]
NModbus.Serial is a seperate package https://www.nuget.org/packages/NModbus.Serial/

On which line are you getting which Exception?

**Comment by wwowa-rus** [comment]
I installed NModbus.Serial and everything works. Thanks.

**Comment by MPapst** [comment]
Can you please close the issue?
