### ISSUE TITLE
Size of lazy Points array should be ushort.MaxValue + 1

### ISSUE THREAD

**Issue by ShashikkYoko** [NModbus/NModbus#94]
Otherwise we are short of one register for both Holding Registers and Input Registers.

**Comment by rquackenbush** [comment]
Quite right! Good catch.

![image](https://user-images.githubusercontent.com/4293870/146380929-7d63a459-bdfd-47df-86d9-7683f83e2554.png)

0xFFFF = 65,535

`const UInt16.MaxValue = 65535;`

Here is some code that demonstrates the problem:

https://dotnetfiddle.net/3BYyp1

**Comment by ShashikkYoko** [comment]
Thanks for a quick response.
When will the change be reflected in the latest Nuget package? 
I saw the code change already, but wondering when will the new formal tested build be available in Nuget?

Regards
Shashi

**Comment by rquackenbush** [comment]
I'm working on getting this built. There are some problems on my AppVeyor
configuration that I'm working through.

**Comment by ShashikkYoko** [comment]
Hope you had a chance to fix the AppVeyor configuration. Your help is much appreciated.

**Comment by rquackenbush** [comment]
Almost there. It looks like all that remains is sorting out a new api key
for nuget. I’m
Hoping to have that done today.

**Comment by rquackenbush** [comment]
Done. Version 3.0.66 has been deployed. Please let me know if you have any further issues or questions.
