### ISSUE TITLE
Read Holding Regist Problems

### ISSUE THREAD

**Issue by jot4p** [NModbus/NModbus#95]
Hi, 

The value readed from address 0 is not correct for one device.

For the same device and same settings:

![image](https://user-images.githubusercontent.com/15892047/146587293-b17a73f8-4356-4536-b241-5ffa39573929.png)

The correct value from address 0 is -21620 ... what is the problem ? 
![image](https://user-images.githubusercontent.com/15892047/146587363-53eb2e20-198d-42b8-aeca-22a79050df93.png)

NModbus 

![image](https://user-images.githubusercontent.com/15892047/146587486-168b275c-b7e7-4498-80c3-30d9fa0cfb9f.png)

Any idea what is wrong ?

**Comment by rquackenbush** [comment]
This is an interesting case. Is this TCP or serial based? If it’s TCP based are you able to get a wire shark capture of each client and attach it here forms to look at?

**Comment by jot4p** [comment]
> This is an interesting case. Is this TCP or serial based? If it’s TCP based are you able to get a wire shark capture of each client and attach it here forms to look at?

Sorry, my fault.. confusion between input regists and holding regists... 

problem solved. 

Thanks
