### ISSUE TITLE
Invisibility of NModbus.Data.RegisterCollection class

### ISSUE THREAD

**Issue by DimaCalugari** [NModbus/NModbus#98]
If you want to create a custom modbus message and you must initialize some specific data, you cannot access the `NModbus.Data.RegisterCollection` class because it is set as `internal`. A `public` access modifier instead would help a lot.

**Comment by code4freee** [comment]
That's right... 
In NModbus4 this class was public, now internal.
For some reasons we have to send function code 100 which is not specified in modbus spec.
If access to internal class, as proposed above, would be granted it would help us very much to change from NModbus4 to actual implementation.

**Comment by DerDan** [comment]
i also need this

**Comment by rquackenbush** [comment]
I've made this class public and it is available as of version 3.0.68 of the NuGet package.
